# Generated by Django 5.1.2 on 2025-05-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastqc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFile',
            new_name='UploadedFileFastQC',
        ),
    ]
