# Generated by Django 5.1.2 on 2025-05-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastqc', '0003_alter_uploadedfilefastqc_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfilefastqc',
            name='file',
            field=models.FileField(upload_to='uploads/fastq/'),
        ),
        migrations.AlterField(
            model_name='uploadedfilefastqc',
            name='result_html',
            field=models.FileField(blank=True, null=True, upload_to='reports/fastq/'),
        ),
    ]
