# Generated by Django 5.1.2 on 2025-05-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfilefastp',
            name='file',
            field=models.FileField(upload_to='uploads/fastp'),
        ),
        migrations.AlterField(
            model_name='uploadedfilefastp',
            name='result_html',
            field=models.FileField(blank=True, null=True, upload_to='reports/fastp'),
        ),
    ]
